### ISSUE TITLE
修正

### ISSUE THREAD

**Issue by nobland** [DecodeLLC/cowrite-web#197]
メイカーで一回下のプレイヤーで組み合わせを再生したのち再度組み合わせて再生すると、再生はされるけど、プレイヤー動かない。

**Comment by nobland** [comment]
マイナー、メジャーの変更が機能していない。もはや、メジャーマイナーがあまり関係なくなってしまっている？？

**Comment by nobland** [comment]
mixの保存（アップロード）が遅い

**Comment by nobland** [comment]
ジャンルを複数選択可能に。あと以下追加&修正お願いします。
Alternative
Blues
Classical
Country
Dance
Electronic
HipHop / Rap
HM / HR
Jazz
J-Pop
Latin
Newage
Pop
R&B
Reggae
Rock
SoundTrack
Techno
Trance
World

**Comment by nobland** [comment]
メイカーの開始位置は、現状からスタート位置を早めることしかできないので、遅らせることもできるようにしたい。

**Comment by alexeypolitov** [comment]
@nobland 個別で登録しました。#228 #229 #230 #231 #232
