### ISSUE TITLE
ジャンルを複数選択可能に。あと以下追加&修正お願いします。

### ISSUE THREAD

**Issue by alexeypolitov** [DecodeLLC/cowrite-web#231]
Alternative
Blues
Classical
Country
Dance
Electronic
HipHop / Rap
HM / HR
Jazz
J-Pop
Latin
Newage
Pop
R&B
Reggae
Rock
SoundTrack
Techno
Trance
World

**Comment by alexeypolitov** [comment]
@nobland 複数選択はトップ画面でよろしいですか？

**Comment by nobland** [comment]
これは検索やUPロードの時も同様です。

**Comment by alexeypolitov** [comment]
@nobland 以前も話しましたが、ジャンルは１つ以上になったら一覧の表示ひ入れなくなります。どうしますか？

**Comment by nobland** [comment]
１個でいきましょう。

**Comment by alexeypolitov** [comment]
@nobland トップ画面などであるフィルターで複数選択可能すればよろしいですか？

<img width="444" alt="screen shot 2017-12-05 at 10 29 44" src="https://user-images.githubusercontent.com/3468058/33585368-41fdf754-d9a7-11e7-8af9-586bc429e2d9.png">

**Comment by nobland** [comment]
いいですね。そうしてください。

**Comment by alexeypolitov** [comment]
@nobland 変更しました。ご確認ください

**Comment by nobland** [comment]
ありがとうございます！
