### ISSUE TITLE
リリックのアップロード可能なファイル形式にdocx、rtf等を対応させたい

### ISSUE THREAD

**Issue by alexeypolitov** [DecodeLLC/cowrite-web#239]

**Comment by alexeypolitov** [comment]
@nobland ウェブ表示でファイルのencodingはutf8になってます。もし、別のencodingでアップすると文字化けになる可能性があります。encodingを変更できるためにインプットを作った方がいいですか？ちなみにdocx/rtfは普通のテキストよりフォーマットされてるテキストも入る可能性がありますがその場合はうまくテキストを読み込めないと思います。txtのみで厳しいですか？

**Comment by nobland** [comment]
なるほど。最初はテキストのみでもいいかもですが。もしくは、これってファイルのUPもしくは、直で打てるようにするということは可能でしょうか。コピーペーストでいけるみたいな。追加で割と大変な作業になるなら、微妙ですが。

**Comment by alexeypolitov** [comment]
@nobland コピーペーストなら入ります。大変ではないです。いかがですか？

**Comment by nobland** [comment]
では、txtとコピーペーストができるようにしてください

**Comment by alexeypolitov** [comment]
@nobland 追加しました。ご確認ください。
<img width="529" alt="screen shot 2017-12-06 at 12 51 05" src="https://user-images.githubusercontent.com/3468058/33643735-6b65a6ae-da84-11e7-8d89-4da7b187af5c.png">

**Comment by nobland** [comment]
完璧です！
