### ISSUE TITLE
インターフェース機能

### ISSUE THREAD

**Issue by nobland** [DecodeLLC/cowrite-web#78]
個別に開始位置設定ができる必要がある

**Comment by nobland** [comment]
全体を同時に再生した時のプレイヤーがない

**Comment by nobland** [comment]
素材に対して、作成者が、コメントを残せるようにしておきたい。
例えば、こんなメロディーを作って欲しいとか。

**Comment by alexeypolitov** [comment]
@nobland #223 #224 #225 個別で登録しました
